"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { DisclaimerFooter } from "@/components/disclaimer-footer"
import {
  ArrowLeft,
  Hotel,
  Map,
  ShoppingBag,
  Utensils,
  Car,
  Sparkles,
  Heart,
  Film,
  Building,
  Users,
  Plane,
  Building2,
  Home,
  MapPinIcon,
  Landmark,
  Trees,
  User,
  Store,
  ShoppingCart,
  Warehouse,
  ShoppingBasket,
  Coffee,
  Wine,
  Bike,
  Bus,
  Ship,
  Scissors,
  PartyPopper,
  Camera,
  Pill,
  Dumbbell,
  Gamepad2,
  Wrench,
} from "lucide-react"
import { MerchantList } from "./merchant-list"

interface SearchDestinationProps {
  onBack: () => void
}

const categories = [
  {
    id: "accommodation",
    name: "Accommodation",
    icon: Hotel,
    description: "Hotels • Resorts • Hostels • Homestays",
    subcategories: [
      { id: "hotels", name: "Hotels", icon: Hotel },
      { id: "resorts", name: "Resorts", icon: Building2 },
      { id: "hostels", name: "Hostels", icon: Home },
      { id: "homestay", name: "Homestay • Rooms for Rent", icon: Home },
      { id: "vacation-rentals", name: "House Vacation Rentals", icon: Building2 },
    ],
  },
  {
    id: "airlines",
    name: "Airlines",
    icon: Plane,
    description: "Flight Bookings • Airlines • Air Travel Services",
    subcategories: [
      { id: "international-airlines", name: "International Airlines", icon: Plane },
      { id: "domestic-airlines", name: "Domestic Airlines", icon: Plane },
      { id: "budget-airlines", name: "Budget Airlines", icon: Plane },
      { id: "charter-flights", name: "Charter Flights", icon: Plane },
    ],
  },
  {
    id: "travel-tourism",
    name: "Travel & Tourism",
    icon: Map,
    description: "Tours • Attractions • Museums • Travel Services",
    subcategories: [
      { id: "tourist-attractions", name: "Tourist Attractions", icon: MapPinIcon },
      { id: "museums", name: "Museums", icon: Landmark },
      { id: "parks", name: "Parks", icon: Trees },
      { id: "tours-agencies", name: "Tours • Travel Agencies", icon: Map },
      { id: "tourist-guides", name: "Tourist Guides", icon: User },
    ],
  },
  {
    id: "shopping",
    name: "Shopping",
    icon: ShoppingBag,
    description: "Markets • Boutiques • Malls • Specialty Shops",
    subcategories: [
      { id: "souvenir-shops", name: "Souvenir Shops", icon: ShoppingBag },
      { id: "local-markets", name: "Local Markets", icon: Store },
      { id: "boutiques", name: "Boutiques", icon: ShoppingCart },
      { id: "malls-stores", name: "Malls • Stores", icon: Warehouse },
      { id: "specialty-shops", name: "Specialty Product Shops", icon: ShoppingBasket },
    ],
  },
  {
    id: "food-beverage",
    name: "Food & Beverage",
    icon: Utensils,
    description: "Restaurants • Cafes • Bars • Dining Experiences",
    subcategories: [
      { id: "restaurants", name: "Restaurants", icon: Utensils },
      { id: "cafes", name: "Cafes", icon: Coffee },
      { id: "bars", name: "Bars • Pubs", icon: Wine },
      { id: "fast-food", name: "Fast Food", icon: ShoppingBasket },
    ],
  },
  {
    id: "transportation",
    name: "Transportation",
    icon: Car,
    description: "Car Dealers • Rentals • Public Transport",
    subcategories: [
      { id: "car-dealers-new", name: "Brand New Cars", icon: Car, parent: "Car Dealers" },
      { id: "car-dealers-used", name: "Second Hand Cars", icon: Car, parent: "Car Dealers" },
      { id: "car-showrooms", name: "Car Showrooms", icon: Car, parent: "Car Dealers" },
      { id: "car-rentals-self", name: "Self Drive Cars for Rent", icon: Car, parent: "Car Rentals" },
      { id: "chauffeur-services", name: "Chauffeur Services", icon: Car, parent: "Car Rentals" },
      { id: "taxis", name: "Taxis", icon: Car, parent: "Public Transport" },
      { id: "motorcycle-taxis", name: "Motorcycle Taxis", icon: Bike, parent: "Public Transport" },
      { id: "shuttle-services", name: "Shuttle Services", icon: Bus, parent: "Public Transport" },
      { id: "van-rentals", name: "Van Rentals", icon: Bus, parent: "Public Transport" },
      { id: "bus-services", name: "Bus Services", icon: Bus, parent: "Public Transport" },
      { id: "bike-rentals", name: "Bike Rentals", icon: Bike, parent: "Other Transport" },
      { id: "escooters", name: "Electric Scooters", icon: Bike, parent: "Other Transport" },
      { id: "boat-rentals", name: "Boat Rentals", icon: Ship, parent: "Other Transport" },
      { id: "ferry-services", name: "Ferry Services", icon: Ship, parent: "Other Transport" },
    ],
  },
  {
    id: "services",
    name: "Services",
    icon: Sparkles,
    description: "Laundry • Salon • Spa • Events • Photography",
    subcategories: [
      { id: "laundry", name: "Laundry", icon: Sparkles },
      { id: "salon-spa", name: "Salon • Spa", icon: Scissors },
      { id: "massage", name: "Massage", icon: Sparkles },
      { id: "event-organizers", name: "Event Organizers", icon: PartyPopper },
      { id: "photographers", name: "Photographers", icon: Camera },
    ],
  },
  {
    id: "health-wellness",
    name: "Health & Wellness",
    icon: Heart,
    description: "Medical Services • Pharmacies • Fitness",
    subcategories: [
      { id: "clinics", name: "Clinics", icon: Heart },
      { id: "pharmacies", name: "Pharmacies", icon: Pill },
      { id: "wellness-centers", name: "Wellness Centers", icon: Heart },
      { id: "fitness-gyms", name: "Fitness Gyms", icon: Dumbbell },
    ],
  },
  {
    id: "entertainment",
    name: "Entertainment & Activities",
    icon: Film,
    description: "Nightlife • Entertainment • Leisure Activities",
    subcategories: [
      { id: "bars-clubs", name: "Bars • Clubs", icon: Wine },
      { id: "cinemas", name: "Cinemas", icon: Film },
      { id: "gaming-centers", name: "Gaming Centers", icon: Gamepad2 },
    ],
  },
  {
    id: "real-estate",
    name: "Real Estate",
    icon: Building,
    description: "Property Rentals • Real Estate Services",
    subcategories: [
      { id: "apartment-rentals", name: "Apartment Rentals", icon: Building },
      { id: "condo-leasing", name: "Condo Leasing", icon: Building2 },
      { id: "real-estate-agents", name: "Real Estate Agents", icon: Home },
    ],
  },
  {
    id: "community-local",
    name: "Community & Local Businesses",
    icon: Users,
    description: "Local Stores • Cooperatives • Community Services",
    subcategories: [
      { id: "small-stores", name: "Small Local Stores", icon: Store },
      { id: "sari-sari", name: "Sari Sari Stores", icon: ShoppingBag },
      { id: "cooperative-shops", name: "Cooperative Shops", icon: Users },
      { id: "repair-shops", name: "Repair Shops", icon: Wrench },
      { id: "tailors", name: "Tailors", icon: Scissors },
    ],
  },
]

// Note: The original 'countries' array is no longer directly used.
// The citiesByCountry object has been renamed to countriesWithCities for clarity.

const countriesWithCities = {
  Afghanistan: ["Kabul", "Kandahar", "Herat", "Mazar-i-Sharif", "Jalalabad", "Kunduz", "Lashkar Gah", "Taloqan"].sort(),
  Albania: ["Tirana", "Durrës", "Vlorë", "Elbasan", "Shkodër", "Fier", "Korçë", "Berat", "Gjirokastër"].sort(),
  Algeria: ["Algiers", "Oran", "Constantine", "Annaba", "Blida", "Batna", "Djelfa", "Sétif", "Sidi Bel Abbès"].sort(),
  Andorra: ["Andorra la Vella", "Escaldes-Engordany", "Encamp", "La Massana", "Sant Julià de Lòria"].sort(),
  Angola: ["Luanda", "Huambo", "Lobito", "Benguela", "Lubango", "Kuito", "Malanje", "Namibe"].sort(),
  Argentina: [
    "Buenos Aires",
    "Córdoba",
    "Rosario",
    "Mendoza",
    "La Plata",
    "San Miguel de Tucumán",
    "Mar del Plata",
    "Salta",
    "Bariloche",
    "Ushuaia",
  ].sort(),
  Armenia: ["Yerevan", "Gyumri", "Vanadzor", "Vagharshapat", "Hrazdan", "Abovyan", "Kapan"].sort(),
  Australia: [
    "Sydney",
    "Melbourne",
    "Brisbane",
    "Perth",
    "Adelaide",
    "Gold Coast",
    "Canberra",
    "Newcastle",
    "Cairns",
    "Darwin",
  ].sort(),
  Austria: ["Vienna", "Salzburg", "Innsbruck", "Graz", "Linz", "Klagenfurt", "Villach", "Hallstatt"].sort(),
  Azerbaijan: ["Baku", "Ganja", "Sumqayit", "Mingachevir", "Lankaran", "Shaki", "Nakhchivan", "Qabala"].sort(),
  Bahamas: ["Nassau", "Freeport", "West End", "Cooper's Town", "Marsh Harbour", "Dunmore Town"].sort(),
  Bahrain: ["Manama", "Riffa", "Muharraq", "Hamad Town", "Isa Town", "Sitra", "Budaiya"].sort(),
  Bangladesh: [
    "Dhaka",
    "Chittagong",
    "Khulna",
    "Rajshahi",
    "Sylhet",
    "Barisal",
    "Rangpur",
    "Mymensingh",
    "Cox's Bazar",
    "Gazipur",
  ].sort(),
  Barbados: ["Bridgetown", "Speightstown", "Oistins", "Bathsheba", "Holetown", "Crane"].sort(),
  Belarus: ["Minsk", "Gomel", "Mogilev", "Vitebsk", "Grodno", "Brest", "Bobruisk"].sort(),
  Belgium: ["Brussels", "Antwerp", "Ghent", "Charleroi", "Liège", "Bruges", "Namur", "Leuven", "Mons"].sort(),
  Belize: ["Belize City", "San Pedro", "Orange Walk", "Belmopan", "Dangriga", "Corozal", "San Ignacio"].sort(),
  Benin: ["Cotonou", "Porto-Novo", "Parakou", "Djougou", "Bohicon", "Kandi", "Abomey", "Natitingou"].sort(),
  Bhutan: [
    "Thimphu",
    "Phuentsholing",
    "Punakha",
    "Paro",
    "Wangdue Phodrang",
    "Jakar",
    "Trashigang",
    "Gelephu",
    "Samdrup Jongkhar",
    "Mongar",
  ].sort(),
  Bolivia: ["La Paz", "Santa Cruz", "Cochabamba", "Sucre", "Oruro", "Potosí", "Tarija", "Uyuni"].sort(),
  "Bosnia and Herzegovina": [
    "Sarajevo",
    "Banja Luka",
    "Tuzla",
    "Zenica",
    "Mostar",
    "Bihać",
    "Prijedor",
    "Trebinje",
  ].sort(),
  Botswana: ["Gaborone", "Francistown", "Maun", "Kasane", "Serowe", "Palapye", "Molepolole"].sort(),
  Brazil: [
    "São Paulo",
    "Rio de Janeiro",
    "Brasília",
    "Salvador",
    "Fortaleza",
    "Belo Horizonte",
    "Manaus",
    "Curitiba",
    "Recife",
    "Porto Alegre",
    "Florianópolis",
    "Foz do Iguaçu",
  ].sort(),
  Brunei: ["Bandar Seri Begawan", "Kuala Belait", "Seria", "Tutong", "Bangar"].sort(),
  Bulgaria: ["Sofia", "Plovdiv", "Varna", "Burgas", "Ruse", "Stara Zagora", "Pleven", "Veliko Tarnovo"].sort(),
  "Burkina Faso": ["Ouagadougou", "Bobo-Dioulasso", "Koudougou", "Ouahigouya", "Banfora", "Dedougou", "Kaya"].sort(),
  Burundi: ["Gitega", "Bujumbura", "Muyinga", "Ngozi", "Ruyigi", "Kayanza", "Bururi"].sort(),
  Cambodia: [
    "Phnom Penh",
    "Siem Reap",
    "Battambang",
    "Sihanoukville",
    "Kampot",
    "Kep",
    "Kampong Cham",
    "Koh Rong",
    "Kratie",
    "Mondulkiri",
  ].sort(),
  Cameroon: ["Yaoundé", "Douala", "Bamenda", "Garoua", "Bafoussam", "Maroua", "Ngaoundéré", "Kribi"].sort(),
  Canada: [
    "Toronto",
    "Montreal",
    "Vancouver",
    "Calgary",
    "Edmonton",
    "Ottawa",
    "Winnipeg",
    "Quebec City",
    "Halifax",
    "Victoria",
    "Banff",
    "Niagara Falls",
  ].sort(),
  "Cape Verde": ["Praia", "Mindelo", "Santa Maria", "Assomada", "São Filipe", "Pedra Badejo"].sort(),
  "Central African Republic": ["Bangui", "Bimbo", "Berbérati", "Carnot", "Bambari", "Bouar", "Bossangoa"].sort(),
  Chad: ["N'Djamena", "Moundou", "Sarh", "Abéché", "Kelo", "Koumra", "Pala", "Am Timan"].sort(),
  Chile: [
    "Santiago",
    "Valparaíso",
    "Concepción",
    "La Serena",
    "Antofagasta",
    "Viña del Mar",
    "Punta Arenas",
    "Puerto Montt",
    "San Pedro de Atacama",
  ].sort(),
  China: [
    "Beijing",
    "Shanghai",
    "Guangzhou",
    "Shenzhen",
    "Chengdu",
    "Hangzhou",
    "Xi'an",
    "Chongqing",
    "Wuhan",
    "Suzhou",
    "Nanjing",
    "Tianjin",
    "Qingdao",
    "Kunming",
    "Guilin",
    "Lijiang",
    "Lhasa",
  ].sort(),
  Colombia: [
    "Bogotá",
    "Medellín",
    "Cali",
    "Barranquilla",
    "Cartagena",
    "Cúcuta",
    "Bucaramanga",
    "Santa Marta",
    "San Andrés",
  ].sort(),
  Comoros: ["Moroni", "Mutsamudu", "Fomboni", "Domoni", "Mitsamiouli"].sort(),
  "Congo (Congo-Brazzaville)": ["Brazzaville", "Pointe-Noire", "Dolisie", "Nkayi", "Mossendjo", "Owando"].sort(),
  "Costa Rica": [
    "San José",
    "Puerto Limón",
    "Alajuela",
    "Liberia",
    "Puntarenas",
    "Tamarindo",
    "Manuel Antonio",
    "La Fortuna",
  ].sort(),
  Croatia: [
    "Zagreb",
    "Split",
    "Rijeka",
    "Osijek",
    "Zadar",
    "Dubrovnik",
    "Pula",
    "Rovinj",
    "Hvar",
    "Korčula",
    "Plitvice",
  ].sort(),
  Cuba: [
    "Havana",
    "Santiago de Cuba",
    "Camagüey",
    "Holguín",
    "Santa Clara",
    "Guantánamo",
    "Varadero",
    "Trinidad",
  ].sort(),
  Cyprus: ["Nicosia", "Limassol", "Larnaca", "Paphos", "Famagusta", "Kyrenia", "Protaras", "Ayia Napa"].sort(),
  "Czech Republic": [
    "Prague",
    "Brno",
    "Ostrava",
    "Plzeň",
    "Liberec",
    "Olomouc",
    "České Budějovice",
    "Karlovy Vary",
  ].sort(),
  "Democratic Republic of the Congo": [
    "Kinshasa",
    "Lubumbashi",
    "Mbuji-Mayi",
    "Kananga",
    "Kisangani",
    "Bukavu",
    "Goma",
  ].sort(),
  Denmark: ["Copenhagen", "Aarhus", "Odense", "Aalborg", "Esbjerg", "Randers", "Kolding", "Helsingør"].sort(),
  Djibouti: ["Djibouti City", "Ali Sabieh", "Tadjoura", "Obock", "Dikhil", "Arta"].sort(),
  Dominica: ["Roseau", "Portsmouth", "Marigot", "Berekua", "Saint Joseph"].sort(),
  "Dominican Republic": [
    "Santo Domingo",
    "Santiago",
    "Punta Cana",
    "La Romana",
    "Puerto Plata",
    "San Cristóbal",
    "Samaná",
    "Las Terrenas",
  ].sort(),
  Ecuador: ["Quito", "Guayaquil", "Cuenca", "Manta", "Loja", "Galápagos Islands", "Montañita", "Baños"].sort(),
  Egypt: ["Cairo", "Alexandria", "Giza", "Luxor", "Aswan", "Sharm El Sheikh", "Hurghada", "Dahab", "Siwa"].sort(),
  "El Salvador": [
    "San Salvador",
    "Santa Ana",
    "San Miguel",
    "Soyapango",
    "La Libertad",
    "El Tunco",
    "Suchitoto",
  ].sort(),
  "Equatorial Guinea": ["Malabo", "Bata", "Ebebiyin", "Aconibe", "Añisoc", "Luba"].sort(),
  Eritrea: ["Asmara", "Massawa", "Keren", "Assab", "Mendefera", "Barentu", "Adi Keyh"].sort(),
  Estonia: ["Tallinn", "Tartu", "Narva", "Pärnu", "Kohtla-Järve", "Viljandi"].sort(),
  Eswatini: ["Mbabane", "Manzini", "Lobamba", "Siteki", "Malkerns", "Piggs Peak"].sort(),
  Ethiopia: ["Addis Ababa", "Dire Dawa", "Mekelle", "Gondar", "Bahir Dar", "Awasa", "Jimma", "Lalibela", "Axum"].sort(),
  Fiji: ["Suva", "Nadi", "Lautoka", "Labasa", "Ba", "Sigatoka", "Savusavu", "Levuka"].sort(),
  Finland: ["Helsinki", "Espoo", "Tampere", "Vantaa", "Oulu", "Turku", "Jyväskylä", "Rovaniemi", "Lapland"].sort(),
  France: [
    "Paris",
    "Marseille",
    "Lyon",
    "Toulouse",
    "Nice",
    "Nantes",
    "Strasbourg",
    "Bordeaux",
    "Lille",
    "Cannes",
    "Avignon",
    "Versailles",
    "Reims",
    "Annecy",
    "Mont Saint-Michel",
  ].sort(),
  Gabon: ["Libreville", "Port-Gentil", "Franceville", "Oyem", "Moanda", "Mouila", "Lambaréné"].sort(),
  Gambia: ["Banjul", "Serekunda", "Brikama", "Bakau", "Farafenni", "Basse Santa Su"].sort(),
  Georgia: ["Tbilisi", "Batumi", "Kutaisi", "Rustavi", "Gori", "Zugdidi", "Mtskheta", "Kazbegi"].sort(),
  Germany: [
    "Berlin",
    "Hamburg",
    "Munich",
    "Cologne",
    "Frankfurt",
    "Stuttgart",
    "Düsseldorf",
    "Dortmund",
    "Essen",
    "Leipzig",
    "Bremen",
    "Dresden",
    "Hanover",
    "Nuremberg",
    "Bonn",
    "Mannheim",
    "Karlsruhe",
  ].sort(),
  Ghana: ["Accra", "Kumasi", "Tamale", "Takoradi", "Ashaiman", "Sunyani", "Cape Coast", "Obuasi", "Elmina"].sort(),
  Greece: [
    "Athens",
    "Thessaloniki",
    "Patras",
    "Heraklion",
    "Larissa",
    "Volos",
    "Rhodes",
    "Santorini",
    "Mykonos",
    "Corfu",
    "Delphi",
    "Meteora",
  ].sort(),
  Grenada: ["St. George's", "Gouyave", "Grenville", "Victoria", "Sauteurs"].sort(),
  Guatemala: [
    "Guatemala City",
    "Antigua",
    "Quetzaltenango",
    "Escuintla",
    "Flores",
    "Tikal",
    "Lake Atitlán",
    "Panajachel",
  ].sort(),
  Guinea: ["Conakry", "Nzérékoré", "Kankan", "Kindia", "Labé", "Mamou", "Siguiri"].sort(),
  "Guinea-Bissau": ["Bissau", "Bafatá", "Gabú", "Bissora", "Bolama", "Cacheu"].sort(),
  Guyana: ["Georgetown", "Linden", "New Amsterdam", "Anna Regina", "Bartica", "Lethem"].sort(),
  Haiti: ["Port-au-Prince", "Cap-Haïtien", "Gonaïves", "Les Cayes", "Port-de-Paix", "Jacmel", "Petionville"].sort(),
  Honduras: ["Tegucigalpa", "San Pedro Sula", "La Ceiba", "Roatán", "Copán", "Utila", "Comayagua", "Tela"].sort(),
  "Hong Kong": [
    "Hong Kong Island",
    "Kowloon",
    "New Territories",
    "Lantau Island",
    "Tsim Sha Tsui",
    "Central",
    "Causeway Bay",
    "Mong Kok",
  ].sort(),
  Hungary: ["Budapest", "Debrecen", "Szeged", "Miskolc", "Pécs", "Győr", "Nyíregyháza", "Eger"].sort(),
  Iceland: ["Reykjavik", "Akureyri", "Keflavik", "Selfoss", "Hafnarfjörður", "Vik", "Höfn"].sort(),
  India: [
    "Mumbai",
    "Delhi",
    "Bangalore",
    "Kolkata",
    "Chennai",
    "Hyderabad",
    "Ahmedabad",
    "Pune",
    "Jaipur",
    "Goa",
    "Varanasi",
    "Agra",
    "Udaipur",
    "Kerala",
    "Rishikesh",
    "Darjeeling",
    "Amritsar",
  ].sort(),
  Indonesia: [
    "Jakarta",
    "Surabaya",
    "Bandung",
    "Medan",
    "Semarang",
    "Bali",
    "Yogyakarta",
    "Makassar",
    "Lombok",
    "Surakarta",
    "Palembang",
    "Batam",
    "Malang",
    "Bogor",
    "Depok",
    "Tangerang",
  ].sort(),
  Iran: ["Tehran", "Mashhad", "Isfahan", "Karaj", "Tabriz", "Shiraz", "Ahvaz", "Qom", "Kermanshah", "Yazd"].sort(),
  Iraq: ["Baghdad", "Basra", "Mosul", "Erbil", "Kirkuk", "Najaf", "Karbala", "Sulaymaniyah", "Nasiriyah"].sort(),
  Ireland: ["Dublin", "Cork", "Limerick", "Galway", "Waterford", "Drogheda", "Kilkenny", "Derry", "Belfast"].sort(),
  Israel: [
    "Jerusalem",
    "Tel Aviv",
    "Haifa",
    "Rishon LeZion",
    "Petah Tikva",
    "Ashdod",
    "Netanya",
    "Beer Sheva",
    "Eilat",
  ].sort(),
  Italy: [
    "Rome",
    "Milan",
    "Naples",
    "Turin",
    "Palermo",
    "Genoa",
    "Bologna",
    "Florence",
    "Venice",
    "Verona",
    "Catania",
    "Bari",
    "Messina",
    "Padua",
    "Trieste",
    "Pisa",
    "Siena",
    "Perugia",
  ].sort(),
  Jamaica: [
    "Kingston",
    "Montego Bay",
    "Spanish Town",
    "Portmore",
    "May Pen",
    "Mandeville",
    "Ocho Rios",
    "Negril",
  ].sort(),
  Japan: [
    "Tokyo",
    "Yokohama",
    "Osaka",
    "Nagoya",
    "Sapporo",
    "Fukuoka",
    "Kobe",
    "Kyoto",
    "Hiroshima",
    "Sendai",
    "Chiba",
    "Nara",
    "Nikko",
    "Hakone",
    "Okinawa",
    "Takayama",
    "Kamakura",
  ].sort(),
  Jordan: ["Amman", "Zarqa", "Irbid", "Aqaba", "Petra", "Jerash", "Madaba", "Wadi Rum", "Dead Sea"].sort(),
  Kazakhstan: [
    "Almaty",
    "Nur-Sultan",
    "Shymkent",
    "Karaganda",
    "Aktobe",
    "Taraz",
    "Pavlodar",
    "Oskemen",
    "Semey",
  ].sort(),
  Kenya: ["Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret", "Malindi", "Naivasha", "Lamu"].sort(),
  Kiribati: ["South Tarawa", "Betio", "Bikenibeu", "Bairiki"].sort(),
  Kuwait: ["Kuwait City", "Hawalli", "Salmiya", "Sabah Al Salem", "Al Ahmadi", "Al Jahra", "Fahaheel"].sort(),
  Kyrgyzstan: ["Bishkek", "Osh", "Jalal-Abad", "Karakol", "Tokmok", "Uzgen", "Naryn", "Talas"].sort(),
  Laos: [
    "Vientiane",
    "Pakse",
    "Savannakhet",
    "Luang Prabang",
    "Thakhek",
    "Xam Neua",
    "Vang Vieng",
    "Phonsavan",
    "Nong Khiaw",
  ].sort(),
  Latvia: ["Riga", "Daugavpils", "Liepāja", "Jelgava", "Jūrmala"].sort(),
  Lebanon: ["Beirut", "Tripoli", "Sidon", "Tyre", "Jounieh", "Baalbek", "Byblos", "Zahle"].sort(),
  Lesotho: ["Maseru", "Teyateyaneng", "Mafeteng", "Hlotse", "Mohale's Hoek", "Maputsoe", "Qacha's Nek"].sort(),
  Liberia: ["Monrovia", "Gbarnga", "Kakata", "Bensonville", "Harper", "Voinjama", "Buchanan"].sort(),
  Libya: ["Tripoli", "Benghazi", "Misrata", "Bayda", "Zawiya", "Ajdabiya", "Tobruk", "Sabha"].sort(),
  Liechtenstein: ["Vaduz", "Schaan", "Balzers", "Triesen", "Eschen"].sort(),
  Lithuania: ["Vilnius", "Kaunas", "Klaipėda", "Šiauliai", "Panevėžys"].sort(),
  Luxembourg: ["Luxembourg City", "Esch-sur-Alzette", "Differdange", "Dudelange", "Ettelbruck"].sort(),
  Macau: ["Macau Peninsula", "Taipa", "Coloane", "Cotai", "Senado Square"].sort(),
  Madagascar: ["Antananarivo", "Toamasina", "Antsirabe", "Mahajanga", "Fianarantsoa", "Toliara", "Antsiranana"].sort(),
  Malawi: ["Lilongwe", "Blantyre", "Mzuzu", "Zomba", "Kasungu", "Mangochi", "Karonga"].sort(),
  Malaysia: [
    "Kuala Lumpur",
    "George Town",
    "Johor Bahru",
    "Malacca",
    "Ipoh",
    "Kuching",
    "Kota Kinabalu",
    "Langkawi",
    "Cameron Highlands",
    "Petaling Jaya",
    "Shah Alam",
    "Putrajaya",
    "Melaka",
    "Penang",
    "Sandakan",
  ].sort(),
  Maldives: ["Malé", "Addu City", "Fuvahmulah", "Kulhudhuffushi", "Thinadhoo"].sort(),
  Mali: ["Bamako", "Sikasso", "Mopti", "Koutiala", "Kayes", "Ségou", "Gao", "Timbuktu"].sort(),
  Malta: ["Valletta", "Birkirkara", "Mosta", "St. Paul's Bay", "Qormi", "Żabbar", "Sliema", "Mdina"].sort(),
  "Marshall Islands": ["Majuro", "Ebeye", "Arno", "Jabat", "Wotje"].sort(),
  Mauritania: ["Nouakchott", "Nouadhibou", "Kiffa", "Kaédi", "Rosso", "Zouérate", "Atar"].sort(),
  Mauritius: ["Port Louis", "Beau Bassin-Rose Hill", "Vacoas-Phoenix", "Curepipe", "Quatre Bornes", "Mahébourg"].sort(),
  Mexico: [
    "Mexico City",
    "Guadalajara",
    "Monterrey",
    "Puebla",
    "Tijuana",
    "León",
    "Juárez",
    "Zapopan",
    "Mérida",
    "San Luis Potosí",
    "Aguascalientes",
    "Cancún",
    "Querétaro",
    "Toluca",
    "Playa del Carmen",
  ].sort(),
  Micronesia: ["Palikir", "Weno", "Kolonia", "Tofol", "Colonia"].sort(),
  Moldova: ["Chișinău", "Tiraspol", "Bălți", "Bender", "Rîbnița", "Cahul", "Ungheni"].sort(),
  Monaco: ["Monaco-Ville", "Monte Carlo", "La Condamine", "Fontvieille"].sort(),
  Mongolia: ["Ulaanbaatar", "Erdenet", "Darkhan", "Choibalsan", "Mörön", "Khovd", "Ölgii"].sort(),
  Montenegro: [
    "Podgorica",
    "Nikšić",
    "Pljevlja",
    "Bijelo Polje",
    "Cetinje",
    "Bar",
    "Herceg Novi",
    "Budva",
    "Kotor",
  ].sort(),
  Morocco: [
    "Casablanca",
    "Rabat",
    "Marrakech",
    "Fez",
    "Tangier",
    "Agadir",
    "Meknes",
    "Oujda",
    "Essaouira",
    "Chefchaouen",
  ].sort(),
  Mozambique: ["Maputo", "Matola", "Beira", "Nampula", "Chimoio", "Nacala", "Quelimane", "Tete", "Inhambane"].sort(),
  Myanmar: [
    "Yangon",
    "Mandalay",
    "Naypyidaw",
    "Bagan",
    "Inle Lake",
    "Ngapali",
    "Mawlamyine",
    "Taunggyi",
    "Pathein",
  ].sort(),
  Namibia: ["Windhoek", "Walvis Bay", "Swakopmund", "Rundu", "Oshakati", "Katima Mulilo", "Otjiwarongo"].sort(),
  Nauru: ["Yaren", "Denigomodu", "Aiwo", "Anabar", "Meneng"].sort(),
  Nepal: [
    "Kathmandu",
    "Pokhara",
    "Lalitpur",
    "Bhaktapur",
    "Biratnagar",
    "Bharatpur",
    "Janakpur",
    "Lumbini",
    "Chitwan",
  ].sort(),
  Netherlands: [
    "Amsterdam",
    "Rotterdam",
    "The Hague",
    "Utrecht",
    "Eindhoven",
    "Tilburg",
    "Groningen",
    "Maastricht",
    "Delft",
  ].sort(),
  "New Zealand": [
    "Auckland",
    "Wellington",
    "Christchurch",
    "Hamilton",
    "Tauranga",
    "Dunedin",
    "Queenstown",
    "Rotorua",
    "Napier",
  ].sort(),
  Nicaragua: ["Managua", "León", "Granada", "Masaya", "Matagalpa", "Estelí", "San Juan del Sur", "Ometepe"].sort(),
  Niger: ["Niamey", "Zinder", "Maradi", "Agadez", "Tahoua", "Dosso", "Arlit"].sort(),
  Nigeria: [
    "Lagos",
    "Kano",
    "Ibadan",
    "Abuja",
    "Port Harcourt",
    "Benin City",
    "Kaduna",
    "Jos",
    "Calabar",
    "Enugu",
  ].sort(),
  "North Korea": ["Pyongyang", "Hamhung", "Chongjin", "Nampo", "Wonsan", "Sinuiju", "Kaesong"].sort(),
  "North Macedonia": ["Skopje", "Bitola", "Kumanovo", "Prilep", "Tetovo", "Veles", "Ohrid", "Strumica"].sort(),
  Norway: ["Oslo", "Bergen", "Trondheim", "Stavanger", "Tromsø", "Drammen", "Ålesund", "Lofoten"].sort(),
  Oman: ["Muscat", "Salalah", "Sohar", "Nizwa", "Sur", "Ibri", "Barka", "Rustaq"].sort(),
  Pakistan: [
    "Karachi",
    "Lahore",
    "Islamabad",
    "Faisalabad",
    "Rawalpindi",
    "Multan",
    "Peshawar",
    "Quetta",
    "Sialkot",
    "Gujranwala",
    "Hunza",
    "Gilgit",
  ].sort(),
  Palau: ["Ngerulmud", "Koror", "Melekeok", "Airai"].sort(),
  Palestine: ["Ramallah", "Gaza", "Hebron", "Nablus", "Bethlehem", "Jericho", "Jenin"].sort(),
  Panama: ["Panama City", "Colón", "David", "La Chorrera", "Bocas del Toro", "Boquete", "El Valle"].sort(),
  "Papua New Guinea": ["Port Moresby", "Lae", "Arawa", "Mount Hagen", "Madang", "Wewak", "Goroka"].sort(),
  Paraguay: ["Asunción", "Ciudad del Este", "Encarnación", "Pedro Juan Caballero", "Luque", "Capiatá"].sort(),
  Peru: [
    "Lima",
    "Cusco",
    "Arequipa",
    "Trujillo",
    "Chiclayo",
    "Iquitos",
    "Huancayo",
    "Piura",
    "Machu Picchu",
    "Puno",
  ].sort(),
  Philippines: [
    "Angeles City",
    "Antipolo",
    "Bacolod",
    "Bacoor",
    "Bago",
    "Baguio",
    "Bais",
    "Batangas City",
    "Bayawan",
    "Biñan",
    "Boracay",
    "Butuan",
    "Cabanatuan",
    "Cadiz",
    "Cagayan de Oro",
    "Calamba",
    "Calapan",
    "Calbayog",
    "Caloocan",
    "Candon",
    "Canlaon",
    "Cauayan",
    "Cavite City",
    "Cebu City",
    "Cotabato City",
    "Dagupan",
    "Danao",
    "Dapitan",
    "Davao City",
    "Dipolog",
    "Dumaguete",
    "El Salvador",
    "General Santos",
    "Gingoog",
    "Guihulngan",
    "Himamaylan",
    "Ilagan",
    "Iligan",
    "Iloilo City",
    "Iriga",
    "Isabela",
    "Kabankalan",
    "Kidapawan",
    "Koronadal",
    "La Carlota",
    "Lamitan",
    "Laoag",
    "Lapu-Lapu",
    "Las Piñas",
    "Legazpi",
    "Ligao",
    "Lipa",
    "Lucena",
    "Maasin",
    "Mabalacat",
    "Makati",
    "Malabon",
    "Malaybalay",
    "Malolos",
    "Mandaluyong",
    "Mandaue",
    "Manila",
    "Marawi",
    "Marikina",
    "Masbate City",
    "Meycauayan",
    "Muñoz",
    "Muntinlupa",
    "Naga (Camarines Sur)",
    "Naga (Cebu)",
    "Navotas",
    "Olongapo",
    "Ormoc",
    "Oroquieta",
    "Ozamiz",
    "Pagadian",
    "Palayan",
    "Palawan (Puerto Princesa)",
    "Panabo",
    "Parañaque",
    "Pasay",
    "Pasig",
    "Passi",
    "Puerto Princesa",
    "Quezon City",
    "Roxas",
    "Sagay",
    "San Carlos (Negros Occidental)",
    "San Carlos (Pangasinan)",
    "San Fernando (La Union)",
    "San Fernando (Pampanga)",
    "San Jose",
    "San Jose del Monte",
    "San Juan",
    "San Pablo",
    "San Pedro",
    "Santa Rosa",
    "Santiago",
    "Siargao",
    "Silay",
    "Sipalay",
    "Sorsogon City",
    "Surigao City",
    "Tabaco",
    "Tabuk",
    "Tacloban",
    "Tacurong",
    "Tagaytay",
    "Tagbilaran",
    "Taguig",
    "Tagum",
    "Talisay (Cebu)",
    "Talisay (Negros Occidental)",
    "Tandag",
    "Tangub",
    "Tanjay",
    "Tarlac City",
    "Tayabas",
    "Toledo",
    "Trece Martires",
    "Tuguegarao",
    "Urdaneta",
    "Valencia",
    "Valenzuela",
    "Victorias",
    "Vigan",
    "Zamboanga City",
  ].sort(),
  Poland: [
    "Warsaw",
    "Kraków",
    "Łódź",
    "Wrocław",
    "Poznań",
    "Gdańsk",
    "Szczecin",
    "Bydgoszcz",
    "Zakopane",
    "Toruń",
  ].sort(),
  Portugal: ["Lisbon", "Porto", "Faro", "Coimbra", "Funchal", "Braga", "Évora", "Sintra", "Lagos", "Albufeira"].sort(),
  Qatar: ["Doha", "Al Wakrah", "Al Rayyan", "Umm Salal", "Al Khor", "Lusail", "Mesaieed"].sort(),
  Romania: [
    "Bucharest",
    "Cluj-Napoca",
    "Timișoara",
    "Iași",
    "Constanța",
    "Craiova",
    "Brașov",
    "Galați",
    "Sibiu",
  ].sort(),
  Russia: [
    "Moscow",
    "Saint Petersburg",
    "Novosibirsk",
    "Yekaterinburg",
    "Kazan",
    "Nizhny Novgorod",
    "Chelyabinsk",
    "Samara",
    "Omsk",
    "Rostov-on-Don",
    "Vladivostok",
    "Sochi",
  ].sort(),
  Rwanda: ["Kigali", "Butare", "Gitarama", "Ruhengeri", "Gisenyi", "Byumba", "Cyangugu"].sort(),
  "Saint Kitts and Nevis": ["Basseterre", "Charlestown", "Dieppe Bay Town", "Sandy Point Town"].sort(),
  "Saint Lucia": ["Castries", "Vieux Fort", "Soufrière", "Gros Islet", "Micoud"].sort(),
  "Saint Vincent and the Grenadines": ["Kingstown", "Georgetown", "Barrouallie", "Port Elizabeth"].sort(),
  Samoa: ["Apia", "Vaitele", "Faleula", "Siusega", "Vaiusu"].sort(),
  "San Marino": ["San Marino", "Serravalle", "Borgo Maggiore", "Domagnano"].sort(),
  "São Tomé and Príncipe": ["São Tomé", "Santana", "Trindade", "Santo António"].sort(),
  "Saudi Arabia": ["Riyadh", "Jeddah", "Mecca", "Medina", "Dammam", "Khobar", "Tabuk", "Abha", "AlUla", "Taif"].sort(),
  Senegal: ["Dakar", "Touba", "Thiès", "Kaolack", "Saint-Louis", "Ziguinchor", "Mbour", "Rufisque"].sort(),
  Serbia: ["Belgrade", "Novi Sad", "Niš", "Kragujevac", "Subotica", "Zrenjanin", "Pančevo", "Čačak"].sort(),
  Seychelles: ["Victoria", "Anse Boileau", "Beau Vallon", "Takamaka", "La Digue"].sort(),
  "Sierra Leone": ["Freetown", "Bo", "Kenema", "Koidu", "Makeni", "Lunsar", "Port Loko"].sort(),
  Singapore: [
    "Singapore City",
    "Jurong",
    "Tampines",
    "Woodlands",
    "Ang Mo Kio",
    "Bedok",
    "Hougang",
    "Sentosa",
    "Marina Bay",
    "Orchard Road",
    "Chinatown",
    "Little India",
    "Bugis",
  ].sort(),
  Slovakia: ["Bratislava", "Košice", "Prešov", "Žilina", "Nitra", "Banská Bystrica", "Trnava", "Trenčín"].sort(),
  Slovenia: ["Ljubljana", "Maribor", "Celje", "Kranj", "Velenje", "Koper", "Novo Mesto", "Bled"].sort(),
  "Solomon Islands": ["Honiara", "Auki", "Gizo", "Buala", "Tulagi", "Kirakira"].sort(),
  Somalia: ["Mogadishu", "Hargeisa", "Bosaso", "Kismayo", "Berbera", "Baidoa", "Galkayo", "Merca"].sort(),
  "South Africa": [
    "Johannesburg",
    "Cape Town",
    "Durban",
    "Pretoria",
    "Port Elizabeth",
    "Bloemfontein",
    "Nelspruit",
    "Polokwane",
    "Kimberley",
    "East London",
  ].sort(),
  "South Korea": [
    "Seoul",
    "Busan",
    "Incheon",
    "Daegu",
    "Daejeon",
    "Gwangju",
    "Suwon",
    "Ulsan",
    "Changwon",
    "Goyang",
    "Yongin",
    "Seongnam",
    "Jeju City",
    "Jeonju",
    "Gyeongju",
    "Sokcho",
  ].sort(),
  "South Sudan": ["Juba", "Malakal", "Wau", "Yei", "Bor", "Bentiu", "Yambio", "Torit"].sort(),
  Spain: [
    "Madrid",
    "Barcelona",
    "Valencia",
    "Seville",
    "Zaragoza",
    "Málaga",
    "Murcia",
    "Palma",
    "Las Palmas",
    "Bilbao",
    "Alicante",
    "Córdoba",
    "Valladolid",
    "Vigo",
    "Gijón",
    "Granada",
    "Toledo",
    "Salamanca",
    "San Sebastián",
  ].sort(),
  "Sri Lanka": [
    "Colombo",
    "Kandy",
    "Galle",
    "Jaffna",
    "Negombo",
    "Anuradhapura",
    "Trincomalee",
    "Batticaloa",
    "Sigiriya",
    "Ella",
    "Nuwara Eliya",
    "Bentota",
    "Mirissa",
  ].sort(),
  Sudan: ["Khartoum", "Omdurman", "Port Sudan", "Kassala", "Nyala", "El-Obeid", "Wad Madani", "El Fasher"].sort(),
  Suriname: ["Paramaribo", "Lelydorp", "Nieuw Nickerie", "Moengo", "Nieuw Amsterdam", "Mariënburg"].sort(),
  Sweden: [
    "Stockholm",
    "Gothenburg",
    "Malmö",
    "Uppsala",
    "Västerås",
    "Örebro",
    "Linköping",
    "Helsingborg",
    "Jönköping",
    "Norrköping",
  ].sort(),
  Switzerland: [
    "Zurich",
    "Geneva",
    "Basel",
    "Lausanne",
    "Bern",
    "Winterthur",
    "Lucerne",
    "St. Gallen",
    "Lugano",
    "Interlaken",
    "Zermatt",
  ].sort(),
  Syria: ["Damascus", "Aleppo", "Homs", "Latakia", "Hama", "Deir ez-Zor", "Raqqa", "Idlib", "Palmyra"].sort(),
  Taiwan: [
    "Taipei",
    "Kaohsiung",
    "Taichung",
    "Tainan",
    "Hsinchu",
    "Keelung",
    "Chiayi",
    "Taoyuan",
    "Hualien",
    "Taroko",
    "Sun Moon Lake",
    "Alishan",
  ].sort(),
  Tajikistan: ["Dushanbe", "Khujand", "Kulob", "Qurghonteppa", "Istaravshan", "Vahdat", "Konibodom"].sort(),
  Tanzania: [
    "Dar es Salaam",
    "Mwanza",
    "Arusha",
    "Dodoma",
    "Mbeya",
    "Morogoro",
    "Tanga",
    "Zanzibar City",
    "Kilimanjaro",
  ].sort(),
  Thailand: [
    "Bangkok",
    "Chiang Mai",
    "Phuket",
    "Pattaya",
    "Krabi",
    "Ayutthaya",
    "Hua Hin",
    "Koh Samui",
    "Chiang Rai",
    "Sukhothai",
    "Koh Phangan",
    "Koh Tao",
    "Pai",
  ].sort(),
  "Timor-Leste": ["Dili", "Baucau", "Maliana", "Suai", "Lospalos", "Aileu"].sort(),
  Togo: ["Lomé", "Sokodé", "Kara", "Kpalimé", "Atakpamé", "Dapaong", "Tsévié"].sort(),
  Tonga: ["Nuku'alofa", "Neiafu", "Haveluloto", "Vaini", "Pangai"].sort(),
  "Trinidad and Tobago": [
    "Port of Spain",
    "San Fernando",
    "Chaguanas",
    "Arima",
    "Scarborough",
    "Point Fortin",
    "Couva",
  ].sort(),
  Tunisia: ["Tunis", "Sfax", "Sousse", "Kairouan", "Bizerte", "Gabès", "Ariana", "Monastir", "Carthage"].sort(),
  Turkey: [
    "Istanbul",
    "Ankara",
    "Izmir",
    "Bursa",
    "Antalya",
    "Adana",
    "Gaziantep",
    "Konya",
    "Mersin",
    "Bodrum",
    "Cappadocia",
    "Pamukkale",
  ].sort(),
  Turkmenistan: ["Ashgabat", "Türkmenabat", "Daşoguz", "Mary", "Balkanabat", "Türkmenbaşy", "Tejen"].sort(),
  Tuvalu: ["Funafuti", "Vaiaku", "Alapi", "Asau"].sort(),
  Uganda: ["Kampala", "Gulu", "Lira", "Mbarara", "Jinja", "Mbale", "Mukono", "Kasese", "Entebbe"].sort(),
  Ukraine: [
    "Kyiv",
    "Kharkiv",
    "Odesa",
    "Dnipro",
    "Donetsk",
    "Zaporizhzhia",
    "Lviv",
    "Kryvyi Rih",
    "Mykolaiv",
    "Mariupol",
  ].sort(),
  "United Arab Emirates": [
    "Dubai",
    "Abu Dhabi",
    "Sharjah",
    "Ajman",
    "Ras Al Khaimah",
    "Fujairah",
    "Al Ain",
    "Umm Al Quwain",
  ].sort(),
  "United Kingdom": [
    "London",
    "Birmingham",
    "Manchester",
    "Glasgow",
    "Liverpool",
    "Leeds",
    "Edinburgh",
    "Bristol",
    "Cardiff",
    "Belfast",
    "Nottingham",
    "Sheffield",
    "Newcastle",
    "Leicester",
    "Brighton",
    "Cambridge",
    "Oxford",
    "York",
    "Bath",
    "Canterbury",
  ].sort(),
  "United States": [
    "New York",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "San Francisco",
    "Austin",
    "Seattle",
    "Denver",
    "Washington D.C.",
    "Boston",
    "Las Vegas",
    "Miami",
    "Orlando",
    "Portland",
    "Nashville",
  ].sort(),
  Uruguay: [
    "Montevideo",
    "Salto",
    "Paysandú",
    "Las Piedras",
    "Rivera",
    "Maldonado",
    "Tacuarembó",
    "Punta del Este",
  ].sort(),
  Uzbekistan: ["Tashkent", "Samarkand", "Namangan", "Andijan", "Bukhara", "Nukus", "Fergana", "Khiva"].sort(),
  Vanuatu: ["Port Vila", "Luganville", "Norsup", "Isangel", "Sola"].sort(),
  "Vatican City": ["Vatican City"].sort(),
  Venezuela: [
    "Caracas",
    "Maracaibo",
    "Valencia",
    "Barquisimeto",
    "Maracay",
    "Ciudad Guayana",
    "Mérida",
    "Barcelona",
  ].sort(),
  Vietnam: [
    "Ho Chi Minh City",
    "Hanoi",
    "Da Nang",
    "Hoi An",
    "Nha Trang",
    "Hue",
    "Halong Bay",
    "Can Tho",
    "Dalat",
    "Phu Quoc",
    "Sapa",
    "Mui Ne",
  ].sort(),
  Yemen: ["Sana'a", "Aden", "Taiz", "Al Hudaydah", "Mukalla", "Ibb", "Dhamar", "Seiyun"].sort(),
  Zambia: ["Lusaka", "Ndola", "Kitwe", "Kabwe", "Chingola", "Mufulira", "Livingstone", "Luanshya"].sort(),
  Zimbabwe: [
    "Harare",
    "Bulawayo",
    "Chitungwiza",
    "Mutare",
    "Gweru",
    "Epworth",
    "Kwekwe",
    "Kadoma",
    "Victoria Falls",
  ].sort(),
}

export function SearchDestination({ onBack }: SearchDestinationProps) {
  const [selectedCountry, setSelectedCountry] = useState("")
  const [selectedCity, setSelectedCity] = useState("")
  const [viewState, setViewState] = useState<"search" | "subcategories" | "merchants">("search")
  const [selectedMainCategory, setSelectedMainCategory] = useState("")
  const [selectedSubcategory, setSelectedSubcategory] = useState("")

  const handleCategoryClick = (categoryId: string) => {
    setSelectedMainCategory(categoryId)
    setViewState("subcategories")
  }

  const handleSubcategoryClick = (subcategoryId: string) => {
    setSelectedSubcategory(subcategoryId)
    setViewState("merchants")
  }

  if (viewState === "merchants") {
    return (
      <MerchantList
        onBack={() => setViewState("subcategories")}
        category={selectedMainCategory}
        subcategory={selectedSubcategory}
      />
    )
  }

  const currentMainCategory = categories.find((c) => c.id === selectedMainCategory)

  if (viewState === "subcategories" && currentMainCategory) {
    return (
      <div className="min-h-screen bg-background">
        <div className="bg-gradient-to-b from-primary/10 to-background">
          <div className="container mx-auto px-4 py-6">
            <Button variant="ghost" onClick={() => setViewState("search")} className="mb-4">
              <ArrowLeft className="mr-2 h-4 w-4" />
              Back to Categories
            </Button>
            <h1 className="text-2xl md:text-3xl font-bold text-foreground">{currentMainCategory.name}</h1>
            <p className="text-muted-foreground mt-2">Select a service type</p>
          </div>
        </div>

        <div className="container mx-auto px-4 py-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {currentMainCategory.subcategories.map((subcategory) => {
              const Icon = subcategory.icon
              return (
                <button
                  key={subcategory.id}
                  onClick={() => handleSubcategoryClick(subcategory.id)}
                  className="p-6 rounded-lg border-2 transition-all text-left border-border bg-background hover:border-violet-700 hover:bg-violet-700/5"
                >
                  <div className="flex items-start gap-4">
                    <div className="p-3 rounded-lg bg-violet-700/10">
                      <Icon className="h-6 w-6 text-violet-700" />
                    </div>
                    <div className="flex-1">
                      <div className="font-semibold text-base">{subcategory.name}</div>
                      {subcategory.parent && (
                        <div className="text-sm text-muted-foreground mt-1">{subcategory.parent}</div>
                      )}
                    </div>
                  </div>
                </button>
              )
            })}
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-background font-sans">
      <div className="bg-gradient-to-b from-primary/10 to-background">
        <div className="container mx-auto px-4 py-6">
          <Button variant="ghost" onClick={onBack} className="mb-4">
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back
          </Button>
          <h1 className="text-2xl md:text-3xl font-bold text-foreground">Search Destinations</h1>
          <p className="text-muted-foreground mt-2">Find Pi-accepting businesses worldwide</p>
        </div>
      </div>

      <div className="container mx-auto px-4 py-6 space-y-6">
        <Card>
          <CardHeader>
            <CardTitle>Where would you like to go?</CardTitle>
            <CardDescription>Select your destination and what you're looking for</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            {/* Country Selection */}
            <div className="space-y-2">
              <label className="text-sm font-medium">Select Country</label>
              <Select value={selectedCountry} onValueChange={setSelectedCountry}>
                <SelectTrigger>
                  <SelectValue placeholder="Choose a country" />
                </SelectTrigger>
                <SelectContent>
                  {Object.keys(countriesWithCities).map((country) => (
                    <SelectItem key={country} value={country}>
                      {country}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            {/* City Selection */}
            {selectedCountry && (
              <div className="space-y-2">
                <label className="text-sm font-medium">Select City</label>
                <Select value={selectedCity} onValueChange={setSelectedCity}>
                  <SelectTrigger>
                    <SelectValue placeholder="Choose a city" />
                  </SelectTrigger>
                  <SelectContent>
                    {countriesWithCities[selectedCountry as keyof typeof countriesWithCities].map((city) => (
                      <SelectItem key={city} value={city}>
                        {city}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            )}

            {/* Category Selection */}
            {selectedCity && (
              <div className="space-y-2">
                <label className="text-sm font-medium">Select Category</label>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                  {categories.map((category) => {
                    const Icon = category.icon
                    return (
                      <button
                        key={category.id}
                        onClick={() => handleCategoryClick(category.id)}
                        className="p-4 rounded-lg border-2 transition-all text-left border-border bg-background hover:border-violet-700 hover:bg-violet-700/5"
                      >
                        <div className="flex items-start gap-3">
                          <Icon className="h-5 w-5 flex-shrink-0 mt-0.5 text-violet-700" />
                          <div>
                            <div className="font-semibold text-sm">{category.name}</div>
                            <div className="text-xs mt-1 text-muted-foreground">{category.description}</div>
                          </div>
                        </div>
                      </button>
                    )
                  })}
                </div>
              </div>
            )}
          </CardContent>
        </Card>
      </div>
      <DisclaimerFooter />
    </div>
  )
}
